### ISSUE TITLE
Enhancement question. Not issue.

### ISSUE THREAD

**Issue by 60plus** [flxhu/volumio_picture_frame#1]
Hi.
First of all, thank you for this plugin/extension.
I have a proposal that will make it even more functional and looking nice.
Would it be possible to make the magic mirror display instead of the photos?

**Comment by flxhu** [comment]
Can you please elaborate.... what should it display instead of photos?

**Comment by 60plus** [comment]
https://github.com/spiffrgr/MagicMirror2
https://github.com/bastilimbach/docker-MagicMirror

![obraz](https://user-images.githubusercontent.com/73450566/205717538-09710d88-0706-46f5-bd93-7b583f702b6f.png)
![obraz](https://user-images.githubusercontent.com/73450566/205719228-bb28575c-1ba3-4ef3-bd04-e8aa81ab2988.png)
![obraz](https://user-images.githubusercontent.com/73450566/205725242-70c77584-78fb-4ac9-83a8-faf57e70219e.png)




Website instead of photos in full screen mode.

Here I found some information about the browser in kiosk mode:

https://sylvaindurand.org/launch-chromium-in-kiosk-mode/
https://stackoverflow.com/questions/31340063/how-to-change-url-on-chromium-kiosk-mode-via-ssh
https://unix.stackexchange.com/questions/475170/how-can-i-enable-touch-events-on-chromium-when-running-in-kiosk-mode


sorry for my english it's not my native language.

**Comment by flxhu** [comment]
Sorry, this picture frame is not based on a browser, so it won't be able to interface with magic mirror.

**Comment by 60plus** [comment]
![obraz](https://user-images.githubusercontent.com/73450566/205956401-cc66073c-9997-41e7-b698-56de8155f80a.png)
This is my it is based on a browser. (WIP)

if your script can display website instead of a photo it will work fine.The only thing is that the browser must be in full screen mode / Kiosk mode and turn off / switch to volumio on tap/ touch

**Comment by flxhu** [comment]
It can't display a website instead of a photo.
